# File & directories
train_dir: "./dataset/raw16k/train/"
train_ctl: "./fmcc_train.ctl"
val_dir: "./dataset/raw16k/test/"
val_ctl: "./fmcc_test_ref.ctl"
result_dir: "./checkpoints"

# Model params
model: 
  target: "BaseMelCNN"
  params: {
    dims: [64, 128, 256, 512],
    dropout: 0.1,
    activation: 'ReLU',
    normalize: 'BatchNorm2d'
  } 

# Optimizer params
optimizer:
  target: "AdamW"
  params: {}

# LR, Scheduler params
lr: 0.0005
scheduler:
  target: "CosineAnnealingLR"
  params: {
    "T_max": 200,
    "eta_min": 0
  }

# Train params
feature_type: "mfcc"
epochs: 50
batch_size: 16
label_smoothing: 0.1

# etc.
seed: 1234
use_wandb: true
wandb_entity: "incheonnationaluniv"
wandb_project: "ML_2024"