# File & directories
train_dir: "./dataset/raw16k/train/"
train_ctl: "./fmcc_train.ctl"
val_dir: "./dataset/raw16k/test/"
val_ctl: "./fmcc_test_ref.ctl"
result_dir: "./checkpoints"

# Model params
model: 
  class: "BaseMelCNN"
  params: {}

# Train params
feature_type: "mel"
epochs: 10
batch_size: 16
optimizer: "Adam"
lr: 0.01

# etc.
seed: 1234
use_wandb: true
wandb_entity: "dnltjdwls1"
wandb_project: "ML_2024"
