# File & directories
train_dir: "./dataset/raw16k/train/"
train_ctl: "./fmcc_train.ctl"
val_dir: "./dataset/raw16k/test/"
val_ctl: "./fmcc_test_ref.ctl"
result_dir: "./checkpoints"

fmax: 4000
n_mfcc: 64

# Model params
model: 
  target: "BaseMelCNN"
  params: {
    in_channel: 1,
    out_channel: 1,
    kernel_size: [7, 7, 7, 7],
    dims: [64, 128, 256, 512],
    do_pooling: [true, true, true, true],
    pooling: 'AvgPool2d',
    dropout: 0.2,
    activation: 'ReLU',
    normalize: 'BatchNorm2d',
    fc_dim: null, # If null, will dynamically calculate the fc dim
  } 

# Optimizer params
optimizer:
  target: "AdamW"
  params: {}

# LR, Scheduler params
lr: 0.0005
scheduler:
  target: "CosineAnnealingLR"
  params: {
    "T_max": 200,
    "eta_min": 0
  }

# Train params
epochs: 100
batch_size: 32
label_smoothing: 0.2

# etc.
debug: false
seed: 1234
use_wandb: true
wandb_entity: "incheonnationaluniv"
wandb_project: "ML_2024"