# File & directories
train_dir: "./dataset/raw16k/train/"
train_ctl: "./fmcc_train.ctl"
val_dir: "./dataset/raw16k/test/"
val_ctl: "./fmcc_test_ref.ctl"
result_dir: "./checkpoints"

# Model params
model: 
  class: "BaseMelCNN"
  params: {
    dims: [64, 64, 128, 128, 256, 256, 512, 512],
    dropout: 0.1,
    activation: 'ReLU',
    normalize: 'BatchNorm2d'
  } 

# Train params
feature_type: "mfcc"
epochs: 50
batch_size: 16
optimizer: "AdamW"
lr: 0.00005
label_smoothing: 0.1
scheduler: ""

# etc.
seed: 1234
use_wandb: true
wandb_entity: "incheonnationaluniv"
wandb_project: "ML_2024"
